### ISSUE TITLE
Quiz "pause café" not being completed

### ISSUE THREAD

**Issue by Cobran53** [marcb152/msft-rewards-bot#2]
Hi again!
After reinstalling and launching again, it worked for most of them ! I closed the precedent issue #(1) due to that. My mobile search and pc search rewards were complete (I do use Bing on mobile, but I don't believe I did 60 searches this morning). 

However, it was unable to complete the quiz "pause café". Here's my error message :
```
10:05:58 - INFO: RewardsValidator (RewardsThread): The following reward is under validation:
        QUIZ:Quiz pause-café   Vous ne connaissez pas une réponse? Recherchez-la sur Bing!   30 points [at line 53]
Exception in thread RewardsThread:
Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "threading.py", line 946, in run
  File "ThreadingLib.py", line 49, in start_rewards
  File "RewardsValidator.py", line 123, in start
  File "RewardsValidator.py", line 60, in validate_reward
  File "selenium\webdriver\remote\webelement.py", line 88, in click
  File "selenium\webdriver\remote\webelement.py", line 396, in _execute
  File "selenium\webdriver\remote\webdriver.py", line 429, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 243, in check_response
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input type="button" value="Commencez à jouer&nbsp;!" id="rqStartQuiz" tabindex="0"> is not clickable at point (154, 528). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: headless chrome=107.0.5304.122)
Stacktrace:
Backtrace:
        Ordinal0 [0x00B6ACD3+2075859]
        Ordinal0 [0x00AFEE61+1633889]
        Ordinal0 [0x009FB7BD+571325]
        Ordinal0 [0x00A31499+791705]
        Ordinal0 [0x00A2F4AC+783532]
        Ordinal0 [0x00A2D0AB+774315]
        Ordinal0 [0x00A2BD37+769335]
        Ordinal0 [0x00A21C76+728182]
        Ordinal0 [0x00A4731C+881436]
        Ordinal0 [0x00A215BF+726463]
        Ordinal0 [0x00A47534+881972]
        Ordinal0 [0x00A5B56A+963946]
        Ordinal0 [0x00A47136+880950]
        Ordinal0 [0x00A1FEFD+720637]
        Ordinal0 [0x00A20F3F+724799]
        GetHandleVerifier [0x00E1EED2+2769538]
        GetHandleVerifier [0x00E10D95+2711877]
        GetHandleVerifier [0x00BFA03A+521194]
        GetHandleVerifier [0x00BF8DA0+516432]
        Ordinal0 [0x00B0682C+1665068]
        Ordinal0 [0x00B0B128+1683752]
        Ordinal0 [0x00B0B215+1683989]
        Ordinal0 [0x00B16484+1729668]
        BaseThreadInitThunk [0x7598FEF9+25]
        RtlGetAppContainerNamedObjectPath [0x779A7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x779A7B8E+238]
```
        
I also had several connection errors, but I believe those are expected under an unstable connection. 
```
10:06:32 - INFO: ThreadingLib (MobileThread): =====AUTO-SEARCH ENDED (MOBILE)===== [at line 34]
10:06:40 - WARNING: connectionpool (MobileThread): Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027BBC1C7910>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/5063ee74e2e633bf27fc81456db05b82 [at line 812]
10:06:44 - WARNING: connectionpool (MobileThread): Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027BBC1C7790>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/5063ee74e2e633bf27fc81456db05b82 [at line 812]
10:06:48 - WARNING: connectionpool (MobileThread): Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027BBC1C78E0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/5063ee74e2e633bf27fc81456db05b82 [at line 812]
10:07:16 - INFO: ThreadingLib (DesktopThread): =====AUTO-SEARCH ENDED===== [at line 67]
10:07:24 - WARNING: connectionpool (DesktopThread): Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027BBC1C73A0>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/0cfd435759905133a8536e19a6a7d4ba [at line 812]
10:07:28 - WARNING: connectionpool (DesktopThread): Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027BBC1C6680>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/0cfd435759905133a8536e19a6a7d4ba [at line 812]
10:07:32 - WARNING: connectionpool (DesktopThread): Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027BBC1C6890>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée')': /session/0cfd435759905133a8536e19a6a7d4ba [at line 812]
10:07:36 - INFO: main (MainThread): Total elapsed seconds: 161.19749426841736
        Total time: 0:02:41.197494 [at line 96]
```

Thanks a lot for your time !

PS : Maybe dumbproof the documentation by stating you should have Chrome opened for it to work... (It's me, I'm the one who needs to be dumbproofed.)

**Comment by marcb152** [comment]
Hello,

The error message suggests that an element is blocking the view, as you can see on this screenshot, a cookie banner prevents the script from interacting with the page. This is now solved in the new release (see [here](https://github.com/marcb152/msft-rewards-bot/releases/tag/V0.7)).
![Capture d’écran 2022-11-27 115639](https://user-images.githubusercontent.com/67200910/204143216-08e74ca3-c2e0-4bcb-9a57-546dd8c89e3f.png)

Regarding the connection warnings, these are happening after the Chrome WebDriver instance is closed. The `connectionpool` package tries to reach this destroyed instance 3 times before giving up. I don't know why it is happening, but I got rid of this annoying warning in the new update.

Btw, Chrome does not need to be opened for the script to work, the script will open it by itself.

You are welcome!
- Marc // πNutStudio // marcb152
